Streaming/Controllers/GeneroController.cs
using Application.Services;
using Application.ViewModels;
using Database.Context;
using Microsoft.AspNetCore.Mvc;

namespace Streaming.Controllers
{
    public class GeneroController : Controller
    {

        public readonly GeneroService _service;

        public GeneroController(ApplicationContext _context)
        {
            _service = new( _context);
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await _service.GetAllGeneroViewModel());
        }

        public IActionResult AddView()
        {
            return View(new GeneroViewModel());
        }

        public async Task<IActionResult> AddAction(GeneroViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View("AddView", model);
            }
            await _service.AddGeneroViewModel(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditView(int id)
        {
            var genero = await _service.GetByIdGeneroViewModel(id);
            return View(genero);
        }

        public async Task<IActionResult> EditAction(GeneroViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("EditView", model);
            }

            await _service.EditGeneroViewModel(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteView(int id)
        {
            var genero = await _service.GetByIdGeneroViewModel(id);
            return View(genero);
        }

        public async Task<IActionResult> DeleteAction(int id)
        {
            await _service.RemoveGeneroViewModel(id);
            return RedirectToAction("Index");
        }

    }
}

Streaming/Controllers/ProductoraController.cs
using Application.Services;
using Application.ViewModels;
using Database.Context;
using Microsoft.AspNetCore.Mvc;

namespace Streaming.Controllers
{
    public class ProductoraController : Controller
    {

        public readonly ProductoraService _service;

        public ProductoraController(ApplicationContext _context)
        {
            _service = new(_context);
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await _service.GetAllProductoraViewModel());
        }

        public IActionResult AddView()
        {
            return View(new ProductoraViewModel());
        }

        public async Task<IActionResult> AddAction(ProductoraViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View("AddView", model);
            }
            await _service.AddProductoraViewModel(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditView(int id)
        {
            var genero = await _service.GetByIdProductoraViewModel(id);
            return View(genero);
        }

        public async Task<IActionResult> EditAction(ProductoraViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("EditView", model);
            }

            await _service.EditProductoraViewModel(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteView(int id)
        {
            var genero = await _service.GetByIdProductoraViewModel(id);
            return View(genero);
        }

        public async Task<IActionResult> DeleteAction(int id)
        {
            await _service.RemoveProductoraViewModel(id);
            return RedirectToAction("Index");
        }
    }
}

Streaming/Controllers/SerieController.cs
using Application.Repositories;
using Application.Services;
using Application.ViewModels;
using Database.Context;
using Microsoft.AspNetCore.Mvc;


namespace Streaming.Controllers
{
    public class SerieController : Controller
    {
        public readonly SerieService _service;

        public ApplicationContext _context;

        public readonly GeneroRepository _grepository;
        public readonly ProductoraRepository _prepository;
        public SerieController(ApplicationContext context)
        {
            _context = context;
            _service = new(context);
            _grepository = new(context);
            _prepository = new(context);

        }

        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllSeriesViewModel());
        }

        public async Task<IActionResult> AddView()
        {
            var generos = await _grepository.GetAllGeneros();
            var productoras = await _prepository.GetAllProductoras();
            ViewBag.Generos = generos.Select(g => new GeneroViewModel { Name = g.Name,  Id = g.Id }).ToList();
            ViewBag.Productoras = productoras.Select(p => new ProductoraViewModel { Name = p.Name, Id = p.Id }).ToList();

            return View(new SerieViewModel());
        }

        public async Task<IActionResult> AddAction(SerieViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var generos = await _grepository.GetAllGeneros();
                var productoras = await _prepository.GetAllProductoras();

                ViewBag.Generos = generos.Select(g => new GeneroViewModel { Name = g.Name, Id = g.Id }).ToList();
                ViewBag.Productoras = productoras.Select(p => new ProductoraViewModel { Name = p.Name, Id = p.Id }).ToList();
                return View("AddView", model);
            }

            await _service.AddSerieViewModel(model);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> EditView(int id) {
            var generos = await _grepository.GetAllGeneros();
            var productoras = await _prepository.GetAllProductoras();

            ViewBag.Generos = generos.Select(g => new GeneroViewModel { Name = g.Name, Id = g.Id }).ToList();
            ViewBag.Productoras = productoras.Select(p => new ProductoraViewModel { Name = p.Name, Id = p.Id }).ToList();

            var serie = await _service.GetByIdSerieViewModel(id);
            return View(serie);
        }

        public async Task<ActionResult> EditAction(SerieViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Generos = (await _grepository.GetAllGeneros()).Select(g => new GeneroViewModel { Name = g.Name, Id = g.Id }).ToList();
                ViewBag.Productoras = (await _prepository.GetAllProductoras()).Select(p => new ProductoraViewModel { Name = p.Name, Id = p.Id }).ToList();
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
                return View("EditView", model);
            }
            await _service.Edit(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteView(int id)
        {
            var serie = await _service.GetByIdSerieViewModel(id);
            return View(serie);
        }

        public async Task<IActionResult> DeleteAction(int id)
        {
            await _service.RemoveSerieViewModel(id);
            return RedirectToAction("Index");
        }



    }
}

Streaming/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Streaming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Streaming.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Streaming</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Serie" asp-action="Index">Series</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Productora" asp-action="Index">Productoras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Genero" asp-action="Index">Generos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Streaming - Jeriel Gomez 20230296
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>